# GCIDE and Roget, compiled by vertrice-dict. The files must be readable by _dictd.
database gcide {
	data	"/usr/local/share/dictd/gcide.dict.dz"
	index	"/usr/local/share/dictd/gcide.index"
}
database roget {
	data	"/usr/local/share/dictd/roget.dict.dz"
	index	"/usr/local/share/dictd/roget.index"
}
